"""slurmdisk -- where your bytes and inodes are, and what ``du`` cannot see.

``du`` is right about bytes, and a correct walker agrees with it byte-for-byte.
What ``du`` cannot tell you is:

* that the tree you just wrote **has not settled**, so the number is low
  (measured on GPFS: 5.58x low, converging over ~60 s);
* that N GB is held by files that were **unlinked while still open**, which have
  no directory entry for any walker to find;
* that the **quota figure you are comparing against is a cached snapshot** of
  some age (measured locally: 28 minutes stale, and not refreshing).

This package answers those three, plus the ordinary question of where the inodes
went, in one pass over the tree.
"""

__all__ = ["__version__"]

# SyntaxError is caught alongside ImportError on purpose: _version.py is
# generated by the build backend, and a backend that emits syntax newer than the
# running interpreter must degrade to an unknown version rather than take the
# whole package down on the oldest interpreter it claims to support.
try:  # pragma: no cover - trivial packaging glue
    from ._version import __version__
except (ImportError, SyntaxError):  # pragma: no cover
    __version__ = "0.0.0+unknown"
